apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXlGenA4aXZrVjgrcDdWeGtHdWZZdE0wSjFMUU10NFl2eHd6a2hFUDQvZVk1Cm5CcFFjRWFqVC9jMEd6bXh1d3hIYnJJczBISFhsMHBQbytRNjdPWWlSRFcxelJETmxpM2daWXRMcTlBdm5oZEkKL2RzMEx2V3VON3VxNUNKOXgxb01ReGF2NEJEV3lXakdzeGVVb08zclRZOW1wTm9wYlRudHlLdUxlR3cyTktRUApLU0p1SytJVlhPMk5Oc0U2WGdhb1NVVE80eERaTE5LUmdnWW54V0FzRTBhZFQwUVlzNjZIc2JGQ2NlOHFwbzh5CjBIYXdnTG1aWmtqckVQZ0RNRHN2MTF5VGxpczJOUXZmNC9sY0pSL0lManA5NmxiT1JqblAvTWNwYzdtK0JXd0YKT1MzQXJ2ekxRZ1RSRHJhSzVPV21kOHRXMmd5ZU43ajFaTS9rblovYzRRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRGcyQlIzZFIzaGc2bjJXSnp4NmlYaVRJcEVndHJVKzBrOWlSaFQrbE1Tcm10NnVaRmI3ClNQQTZnN0VnZGdncWtSVjFxek8xNTJDUUNxSkkwSVF0QTRqa0R6K3V1NFlIU255WVdtUC9zb2hBSDFLWTNGSjUKRnhFVjBseXIrY3J3TnNCVVNLdklNUmZzS3hCdHFqQVpoelZxdmd3dUxhdTJPZ0FvNmdDeGdkNFptZ3l2TmJyNApvQ3ZoeTI3Z2l3RkVIV0M0Zys1ZnJxNnRNOStiaThuTFd1KzFWajF4a0h0YUl2SUlPaXBoa09XN0FlMUpvNUdXCnRwT2pocGw1ZlN2M085UFhtVjBTTU5sSW9oWjJuSWZpa2ttUHF5WnhUajBFQStwdVBrQ3hBRktXeHdCRU12Q1kKRzFJZ2E4UHZFZ1c5UWpLVUk3QXlaYzhFd2xoR1MrVWs3SnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
