apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusteradmin-role-binding
subjects:
- kind: User
  name: Cluster-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-admin-role
  apiGroup: rbac.authorization.k8s.io
